# Generated by Django 6.1 on 2026-08-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_galleryphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('school', 'School Event'), ('travel', 'Travel'), ('my family', 'MY Family'), ('sports', 'Sports Teams'), ('other', 'Other')], default='personal', max_length=50),
        ),
    ]
