# Generated by Django 6.0.4 on 2026-08-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='💻', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Computer & Technology Training Program', max_length=200)),
                ('description', models.TextField(default='Practical technology training designed for students, beginners and aspiring developers.')),
                ('online_classes', models.BooleanField(default=True)),
                ('offline_classes', models.BooleanField(default=True)),
                ('languages', models.CharField(default='🇳🇵 नेपाली, 🇬🇧 English, 🇮🇳 हिन्दी', max_length=255)),
                ('esewa_qr', models.ImageField(blank=True, null=True, upload_to='training/qr/')),
                ('khalti_qr', models.ImageField(blank=True, null=True, upload_to='training/qr/')),
                ('bank_qr', models.ImageField(blank=True, null=True, upload_to='training/qr/')),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('payment_method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank', 'Bank')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=150)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='training/payments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='hero.trainingservice'),
        ),
    ]
