# Generated by Django 6.0.4 on 2026-08-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_seed_training_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('course', models.CharField(choices=[('Basic Computer', 'Basic Computer'), ('Web Design', 'Web Design'), ('3D Print Design', '3D Print Design'), ('Full Stack Development', 'Full Stack Development'), ('Graphic Design', 'Graphic Design'), ('Python Programming', 'Python Programming'), ('Digital Marketing', 'Digital Marketing')], max_length=100)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical'), ('Both', 'Online + Physical')], max_length=30)),
                ('duration', models.CharField(max_length=100)),
                ('preferred_session', models.CharField(max_length=100)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('admission_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
